-- MySQL Script generated by MySQL Workbench
-- Fri Nov  7 13:36:14 2025
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Cajuru
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cajuru
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cajuru` ;
USE `Cajuru` ;

-- -----------------------------------------------------
-- Table `Cajuru`.`voluntario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`voluntario` (
  `idvoluntario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo_cracha` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `sobrenome` VARCHAR(255) NOT NULL DEFAULT '',
  `cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `rg` VARCHAR(9) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `estado_civil` ENUM('Solteiro', 'Casado', 'Separado', 'Divorciado', 'Viúvo') NOT NULL,
  PRIMARY KEY (`idvoluntario`),
  UNIQUE INDEX `idvoluntario_UNIQUE` (`idvoluntario` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC),
  UNIQUE INDEX `codigo_cracha_UNIQUE` (`codigo_cracha` ASC),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`voluntariado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`voluntariado` (
  `idvoluntariado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `voluntario_idvoluntario` INT UNSIGNED NOT NULL,
  `hospital` ENUM('HMC', 'HUC') NOT NULL,
  `atividade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvoluntariado`),
  UNIQUE INDEX `idvoluntariado_UNIQUE` (`idvoluntariado` ASC),
  INDEX `fk_voluntariado_voluntario1_idx` (`voluntario_idvoluntario` ASC),
  CONSTRAINT `fk_voluntariado_voluntario1`
    FOREIGN KEY (`voluntario_idvoluntario`)
    REFERENCES `Cajuru`.`voluntario` (`idvoluntario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`escala_voluntario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`escala_voluntario` (
  `idescala_voluntario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `voluntariado_idvoluntariado` INT UNSIGNED NOT NULL,
  `dia_semana` ENUM('domingo', 'segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado') NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  PRIMARY KEY (`idescala_voluntario`),
  UNIQUE INDEX `idescala_voluntario_UNIQUE` (`idescala_voluntario` ASC),
  INDEX `fk_escala_voluntario_voluntariado1_idx` (`voluntariado_idvoluntariado` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Cajuru`.`intencao_volunt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`intencao_volunt` (
  `idintencao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hospital` ENUM('HMC', 'HUC') NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `sobrenome` VARCHAR(255) NOT NULL DEFAULT '',
  `data_nascimento` DATE NULL,
  `local_nascimento` VARCHAR(100) NULL,
  `rg` VARCHAR(20) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `estado_civil` ENUM('Solteiro', 'Casado', 'Separado', 'Divorciado', 'Viúvo') NULL,
  `nome_conjuge` VARCHAR(255) NULL,
  `nome_pai` VARCHAR(255) NULL,
  `nome_mae` VARCHAR(255) NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(20) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `cep` VARCHAR(12) NULL,
  `telefone_residencial` VARCHAR(20) NULL,
  `celular` VARCHAR(20) NOT NULL,
  `religiao` VARCHAR(100) NULL,
  `email` VARCHAR(255) NOT NULL,
  `escolaridade_curso` VARCHAR(100) NULL,
  `local_trabalho` VARCHAR(100) NULL,
  `telefone_trabalho` VARCHAR(20) NULL,
  `ocupacao` ENUM('aposentado', 'empregado', 'autonomo', 'do lar', 'outro') NULL,
  `ocupacao_outro` VARCHAR(100) NULL,
  `acomp_med` VARCHAR(255) NULL,
  `transporte` VARCHAR(100) NULL,
  `ficou_sab` VARCHAR(255) NULL,
  `ja_volunt` TINYINT(1) NULL,
  `ja_volunt_onde` VARCHAR(255) NULL,
  `faz_volunt` VARCHAR(255) NULL,
  `group_volunteer` VARCHAR(255) NULL,
  `contrib_ser` TEXT NULL,
  `hab_musical` TINYINT(1) NULL,
  `hab_musical_qual` VARCHAR(255) NULL,
  `aux_alimentacao` TINYINT(1) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idintencao`),
  UNIQUE INDEX `idvoluntario_intencao_UNIQUE` (`idintencao` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`escala_intencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`escala_intencao` (
  `idescala_intencao` INT NOT NULL AUTO_INCREMENT,
  `intencao_idintencao` INT UNSIGNED NOT NULL,
  `dia_semana` ENUM('domingo', 'segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado') NOT NULL,
  `hora_inicio` TIME NULL,
  `hora_fim` TIME NULL,
  PRIMARY KEY (`idescala_intencao`),
  UNIQUE INDEX `idescala_intencao_UNIQUE` (`idescala_intencao` ASC),
  INDEX `fk_escala_intencao_intencao1_idx` (`intencao_idintencao` ASC),
  CONSTRAINT `fk_escala_intencao_intencao1`
    FOREIGN KEY (`intencao_idintencao`)
    REFERENCES `Cajuru`.`intencao_volunt` (`idintencao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`status_intencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`status_intencao` (
  `idstatus_intencao` INT NOT NULL AUTO_INCREMENT,
  `intencao_idintencao` INT UNSIGNED NOT NULL,
  `aprovado` TINYINT(1) NOT NULL,
  `motivo` VARCHAR(255) NULL,
  `data_inicio` DATE NULL,
  `atividade` VARCHAR(45) NULL,
  `anotacoes` VARCHAR(255) NULL,
  `data_acolher` DATE NULL,
  `data_cav` DATE NULL,
  `inicio_vacinas` DATE NULL,
  `final_vacinas` DATE NULL,
  `data_foto` DATE NULL,
  `data_cracha` DATE NULL,
  `formacao_particip` TINYINT(1) NULL,
  `formacao_mod1` DATE NULL,
  `formacao_mod2` DATE NULL,
  `formacao_mod3` DATE NULL,
  PRIMARY KEY (`idstatus_intencao`),
  UNIQUE INDEX `idstatus_intencao_UNIQUE` (`idstatus_intencao` ASC),
  INDEX `fk_status_intencao_intencao1_idx` (`intencao_idintencao` ASC),
  CONSTRAINT `fk_status_intencao_intencao1`
    FOREIGN KEY (`intencao_idintencao`)
    REFERENCES `Cajuru`.`intencao_volunt` (`idintencao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`metrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`metrica` (
  `idmetrica` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmetrica`),
  UNIQUE INDEX `idmetrica_UNIQUE` (`idmetrica` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`atividade` (
  `idatividade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL,
  `emoji` VARCHAR(10) NULL,
  `local` VARCHAR(100) NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`idatividade`),
  UNIQUE INDEX `idatividade_UNIQUE` (`idatividade` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`atividade_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`atividade_assignment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `atividade_idatividade` INT UNSIGNED NOT NULL,
  `voluntario_idvoluntario` INT UNSIGNED NOT NULL,
  `assigned_at` DATETIME NOT NULL,
  `removed_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividade_assignment_atividade_idx` (`atividade_idatividade` ASC),
  INDEX `fk_atividade_assignment_voluntario_idx` (`voluntario_idvoluntario` ASC),
  CONSTRAINT `fk_atividade_assignment_atividade`
    FOREIGN KEY (`atividade_idatividade`)
    REFERENCES `Cajuru`.`atividade` (`idatividade`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividade_assignment_voluntario`
    FOREIGN KEY (`voluntario_idvoluntario`)
    REFERENCES `Cajuru`.`voluntario` (`idvoluntario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`metrica_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`metrica_atividade` (
  `metrica_idmetrica` INT UNSIGNED NOT NULL,
  `atividade_idatividade` INT UNSIGNED NOT NULL,
  `idmetrica_atividade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  INDEX `fk_metrica_atividade_metrica1_idx` (`metrica_idmetrica` ASC),
  INDEX `fk_metrica_atividade_atividade1_idx` (`atividade_idatividade` ASC),
  PRIMARY KEY (`idmetrica_atividade`),
  UNIQUE INDEX `idmetrica_atividade_UNIQUE` (`idmetrica_atividade` ASC),
  CONSTRAINT `fk_metrica_atividade_metrica1`
    FOREIGN KEY (`metrica_idmetrica`)
    REFERENCES `Cajuru`.`metrica` (`idmetrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_metrica_atividade_atividade1`
    FOREIGN KEY (`atividade_idatividade`)
    REFERENCES `Cajuru`.`atividade` (`idatividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`reg_manual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`reg_manual` (
  `idreg_manual` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idmetrica_atividade` INT UNSIGNED NOT NULL,
  `data` DATE NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`idreg_manual`),
  UNIQUE INDEX `idindicadores_volunt_UNIQUE` (`idreg_manual` ASC),
  INDEX `fk_indicadores_volunt_metrica_atividade1_idx` (`idmetrica_atividade` ASC),
  CONSTRAINT `fk_indicadores_volunt_metrica_atividade1`
    FOREIGN KEY (`idmetrica_atividade`)
    REFERENCES `Cajuru`.`metrica_atividade` (`idmetrica_atividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`vol_atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`vol_atividades` (
  `idvol_atividades` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idvoluntario` INT UNSIGNED NOT NULL,
  `idmetrica_atividade` INT UNSIGNED NOT NULL,
  `data_hora` TIMESTAMP(2) NOT NULL,
  PRIMARY KEY (`idvol_atividades`),
  UNIQUE INDEX `idvol_atividades_UNIQUE` (`idvol_atividades` ASC),
  INDEX `fk_vol_atividades_voluntario1_idx` (`idvoluntario` ASC),
  INDEX `fk_vol_atividades_metrica_atividade1_idx` (`idmetrica_atividade` ASC),
  CONSTRAINT `fk_vol_atividades_voluntario1`
    FOREIGN KEY (`idvoluntario`)
    REFERENCES `Cajuru`.`voluntario` (`idvoluntario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vol_atividades_metrica_atividade1`
    FOREIGN KEY (`idmetrica_atividade`)
    REFERENCES `Cajuru`.`metrica_atividade` (`idmetrica_atividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`reg_atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`reg_atividades` (
  `idreg_atividades` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idmetrica_atividade` INT UNSIGNED NOT NULL,
  `vol_atividades_idvol_atividades` INT UNSIGNED NOT NULL,
  `reg_manual_idreg_manual` INT UNSIGNED NOT NULL,
  `reg_atividadescol` DATE NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`idreg_atividades`),
  UNIQUE INDEX `idreg_atendimentos_UNIQUE` (`idreg_atividades` ASC),
  INDEX `fk_reg_atividades_metrica_atividade1_idx` (`idmetrica_atividade` ASC),
  INDEX `fk_reg_atividades_vol_atividades1_idx` (`vol_atividades_idvol_atividades` ASC),
  INDEX `fk_reg_atividades_reg_manual1_idx` (`reg_manual_idreg_manual` ASC),
  CONSTRAINT `fk_reg_atividades_metrica_atividade1`
    FOREIGN KEY (`idmetrica_atividade`)
    REFERENCES `Cajuru`.`metrica_atividade` (`idmetrica_atividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reg_atividades_vol_atividades1`
    FOREIGN KEY (`vol_atividades_idvol_atividades`)
    REFERENCES `Cajuru`.`vol_atividades` (`idvol_atividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reg_atividades_reg_manual1`
    FOREIGN KEY (`reg_manual_idreg_manual`)
    REFERENCES `Cajuru`.`reg_manual` (`idreg_manual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`presenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`presenca` (
  `idpresenca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idvoluntariado` INT UNSIGNED NOT NULL,
  `idescala_voluntario` INT UNSIGNED NULL,
  `hora_entrada` TIMESTAMP(2) NOT NULL,
  `hora_saida` TIMESTAMP(2) NOT NULL,
  `status_presenca` ENUM('presente', 'finalizado') NOT NULL,
  PRIMARY KEY (`idpresenca`),
  UNIQUE INDEX `idpresenca_UNIQUE` (`idpresenca` ASC),
  INDEX `fk_presenca_voluntariado1_idx` (`idvoluntariado` ASC),
  INDEX `fk_presenca_escala_voluntario1_idx` (`idescala_voluntario` ASC),
  CONSTRAINT `fk_presenca_voluntariado1`
    FOREIGN KEY (`idvoluntariado`)
    REFERENCES `Cajuru`.`voluntariado` (`idvoluntariado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presenca_escala_voluntario1`
    FOREIGN KEY (`idescala_voluntario`)
    REFERENCES `Cajuru`.`escala_voluntario` (`idescala_voluntario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`local` (
  `idlocal` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local_idlocal` INT UNSIGNED NULL,
  `hospital` ENUM('HMC', 'HUC') NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idlocal`),
  UNIQUE INDEX `idlocal_UNIQUE` (`idlocal` ASC),
  INDEX `fk_local_local1_idx` (`local_idlocal` ASC),
  CONSTRAINT `fk_local_local1`
    FOREIGN KEY (`local_idlocal`)
    REFERENCES `Cajuru`.`local` (`idlocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`sala` (
  `idsala` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hospital` ENUM('HMC', 'HUC') NOT NULL,
  `codigo_sala` VARCHAR(45) NOT NULL,
  `nome_sala` VARCHAR(45) NULL,
  `capacidade` INT NULL,
  `local_idlocal` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idsala`),
  UNIQUE INDEX `idsala_UNIQUE` (`idsala` ASC),
  INDEX `fk_sala_local1_idx` (`local_idlocal` ASC),
  CONSTRAINT `fk_sala_local1`
    FOREIGN KEY (`local_idlocal`)
    REFERENCES `Cajuru`.`local` (`idlocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`reserva_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`reserva_sala` (
  `idreserva` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hora_inicio` DATETIME NOT NULL,
  `hora_fim` DATETIME NOT NULL,
  `status` ENUM('reservada', 'ocupada', 'livre') NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `sala_idsala` INT UNSIGNED NOT NULL,
  `voluntariado_idvoluntariado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idreserva`),
  UNIQUE INDEX `idreserva_UNIQUE` (`idreserva` ASC),
  INDEX `fk_reserva_sala_sala1_idx` (`sala_idsala` ASC),
  INDEX `fk_reserva_sala_voluntariado1_idx` (`voluntariado_idvoluntariado` ASC),
  CONSTRAINT `fk_reserva_sala_sala1`
    FOREIGN KEY (`sala_idsala`)
    REFERENCES `Cajuru`.`sala` (`idsala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_sala_voluntariado1`
    FOREIGN KEY (`voluntariado_idvoluntariado`)
    REFERENCES `Cajuru`.`voluntariado` (`idvoluntariado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`reserva_participantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`reserva_participantes` (
  `idreserva_participantes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reserva_sala_idreserva` INT UNSIGNED NOT NULL,
  `voluntariado_idvoluntariado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idreserva_participantes`),
  UNIQUE INDEX `idreserva_participantes_UNIQUE` (`idreserva_participantes` ASC),
  INDEX `fk_reserva_participantes_reserva_sala1_idx` (`reserva_sala_idreserva` ASC),
  INDEX `fk_reserva_participantes_voluntariado1_idx` (`voluntariado_idvoluntariado` ASC),
  CONSTRAINT `fk_reserva_participantes_reserva_sala1`
    FOREIGN KEY (`reserva_sala_idreserva`)
    REFERENCES `Cajuru`.`reserva_sala` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_participantes_voluntariado1`
    FOREIGN KEY (`voluntariado_idvoluntariado`)
    REFERENCES `Cajuru`.`voluntariado` (`idvoluntariado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`papel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`papel` (
  `idpapel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_papel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpapel`),
  UNIQUE INDEX `idpapel_UNIQUE` (`idpapel` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`usuario` (
  `idusuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `papel_idpapel` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `sobrenome` VARCHAR(255) NOT NULL DEFAULT '',
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC),
  INDEX `fk_usuario_papel1_idx` (`papel_idpapel` ASC),
  CONSTRAINT `fk_usuario_papel1`
    FOREIGN KEY (`papel_idpapel`)
    REFERENCES `Cajuru`.`papel` (`idpapel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`dispositivo_iot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`dispositivo_iot` (
  `iddispositivo_iot` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo_identificador` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`iddispositivo_iot`),
  UNIQUE INDEX `iddispositivo_iot_UNIQUE` (`iddispositivo_iot` ASC),
  UNIQUE INDEX `codigo_identificador_UNIQUE` (`codigo_identificador` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`log_iot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`log_iot` (
  `idlog_iot` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `iddispositivo_iot` INT UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP(2) NOT NULL,
  `mensagem` TEXT NOT NULL,
  PRIMARY KEY (`idlog_iot`),
  UNIQUE INDEX `idlog_iot_UNIQUE` (`idlog_iot` ASC),
  INDEX `fk_log_iot_dispositivo_iot1_idx` (`iddispositivo_iot` ASC),
  CONSTRAINT `fk_log_iot_dispositivo_iot1`
    FOREIGN KEY (`iddispositivo_iot`)
    REFERENCES `Cajuru`.`dispositivo_iot` (`iddispositivo_iot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`evento` (
  `idevento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descrição` VARCHAR(100) NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NULL,
  PRIMARY KEY (`idevento`),
  UNIQUE INDEX `idevento_UNIQUE` (`idevento` ASC),
  INDEX `fk_evento_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_evento_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `Cajuru`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cajuru`.`vol_local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cajuru`.`vol_local` (
  `idvol_local` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local_idlocal` INT UNSIGNED NOT NULL,
  `voluntario_idvoluntario` INT UNSIGNED NOT NULL,
  `hora_entrada` TIMESTAMP(2) NOT NULL,
  `hora_saida` TIMESTAMP(2) NULL,
  `sala_idsala` INT UNSIGNED NULL,
  PRIMARY KEY (`idvol_local`),
  UNIQUE INDEX `idvol_local_UNIQUE` (`idvol_local` ASC),
  INDEX `fk_vol_local_local1_idx` (`local_idlocal` ASC),
  INDEX `fk_vol_local_voluntario1_idx` (`voluntario_idvoluntario` ASC),
  INDEX `fk_vol_local_sala1_idx` (`sala_idsala` ASC),
  CONSTRAINT `fk_vol_local_local1`
    FOREIGN KEY (`local_idlocal`)
    REFERENCES `Cajuru`.`local` (`idlocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vol_local_voluntario1`
    FOREIGN KEY (`voluntario_idvoluntario`)
    REFERENCES `Cajuru`.`voluntario` (`idvoluntario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vol_local_sala1`
    FOREIGN KEY (`sala_idsala`)
    REFERENCES `Cajuru`.`sala` (`idsala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;










DELIMITER $$

CREATE TRIGGER trg_vol_atividades_after_insert
AFTER INSERT ON vol_atividades
FOR EACH ROW
BEGIN
    INSERT INTO reg_atividades (
        idmetrica_atividade,
        data_referencia,
        quantidade,
        vol_atividades_idvol_atividades
    )
    VALUES (
        NEW.idmetrica_atividade,
        DATE(NEW.data_hora), -- Extrai apenas a parte da data do TIMESTAMP
        1,                   -- Cada registro automático conta como 1
        NEW.idvol_atividades -- Mantém o link com a origem
    );
END$$

DELIMITER ;



DELIMITER $$

CREATE TRIGGER trg_reg_manual_after_insert
AFTER INSERT ON reg_manual
FOR EACH ROW
BEGIN
    INSERT INTO reg_atividades (
        idmetrica_atividade,
        data_referencia,
        quantidade,
        reg_manual_idreg_manual
    )
    VALUES (
        NEW.idmetrica_atividade,
        NEW.data,
        NEW.quantidade,
        NEW.idreg_manual -- Mantém o link com a origem
    );
END$$

DELIMITER ;


CREATE VIEW vw_indicadores_voluntariado AS
SELECT
    RA.data_referencia AS data,
    A.nome AS atividade,
    M.nome AS metrica,
    RA.quantidade
FROM
    reg_atividades RA
    INNER JOIN metrica_atividade MA ON RA.idmetrica_atividade = MA.idmetrica_atividade
    INNER JOIN atividade A ON MA.atividade_idatividade = A.idatividade
    INNER JOIN metrica M ON MA.metrica_idmetrica = M.idmetrica;
    
    


CREATE OR REPLACE VIEW vw_lista_presenca AS
SELECT 
    p.idpresenca,
    v.codigo_cracha,
    v.nome AS nome_voluntario,
    vd.hospital,
    vd.atividade,
    DATE_FORMAT(p.hora_entrada, '%H:%i') AS horario_entrada,
    DATE_FORMAT(p.hora_saida, '%H:%i') AS horario_saida,
    p.status_presenca
FROM presenca p
INNER JOIN voluntariado vd ON p.idvoluntariado = vd.idvoluntariado
INNER JOIN voluntario v ON vd.voluntario_idvoluntario = v.idvoluntario
WHERE DATE(p.hora_entrada) = CURDATE();
    
    
    
CREATE OR REPLACE VIEW vw_frequencia_individual AS
SELECT 
    v.idvoluntario,
    v.nome,
    -- Total de registros (presenças + faltas registradas)
    COUNT(p.idpresenca) AS total_escalas_registradas,
    -- Conta 'presente' ou 'finalizado' como comparecimento
    SUM(CASE WHEN p.status_presenca IN ('presente', 'finalizado') THEN 1 ELSE 0 END) AS total_presencas,
    -- Conta 'falta' apenas se você registrar explicitamente
    SUM(CASE WHEN p.status_presenca = 'falta' THEN 1 ELSE 0 END) AS total_faltas,
    -- Cálculo da porcentagem (evita divisão por zero)
    IF(COUNT(p.idpresenca) > 0, 
       ROUND((SUM(CASE WHEN p.status_presenca IN ('presente', 'finalizado') THEN 1 ELSE 0 END) / COUNT(p.idpresenca)) * 100, 1), 
       0) AS porcentagem_presenca
FROM voluntario v
LEFT JOIN voluntariado vd ON v.idvoluntario = vd.voluntario_idvoluntario
LEFT JOIN presenca p ON vd.idvoluntariado = p.idvoluntariado
GROUP BY v.idvoluntario, v.nome;



CREATE OR REPLACE VIEW vw_frequencia_geral AS
SELECT 
    COUNT(p.idpresenca) AS total_registros_instituicao,
    SUM(CASE WHEN p.status_presenca IN ('presente', 'finalizado') THEN 1 ELSE 0 END) AS total_presencas_geral,
    SUM(CASE WHEN p.status_presenca = 'falta' THEN 1 ELSE 0 END) AS total_faltas_geral,
    IF(COUNT(p.idpresenca) > 0, 
       ROUND((SUM(CASE WHEN p.status_presenca IN ('presente', 'finalizado') THEN 1 ELSE 0 END) / COUNT(p.idpresenca)) * 100, 1), 
       0) AS taxa_assiduidade_geral
FROM presenca p;


CREATE OR REPLACE VIEW vw_salas_livres_agora AS
SELECT 
    s.idsala,
    s.hospital,
    s.codigo_sala,
    s.nome_sala,
    s.capacidade,
    l.nome AS nome_local
FROM sala s
LEFT JOIN local l ON s.local_idlocal = l.idlocal
WHERE 
    -- Critério 1: NÃO pode estar em uma reserva ativa agora
    s.idsala NOT IN (
        SELECT sala_idsala 
        FROM reserva_sala rs 
        WHERE rs.status IN ('reservada', 'ocupada')
          AND NOW() BETWEEN rs.hora_inicio AND rs.hora_fim
    )
    AND
    -- Critério 2: NÃO pode estar ocupada por um voluntário agora
    s.idsala NOT IN (
        SELECT sala_idsala 
        FROM vol_local vl 
        WHERE vl.sala_idsala IS NOT NULL
          -- Verifica se 'agora' é maior que a entrada E (ainda não saiu OU 'agora' é menor que a saída)
          -- CAST usado para tentar forçar a comparação correta mesmo sendo VARCHAR
          AND NOW() >= CAST(vl.hora_entrada AS DATETIME)
          AND (vl.hora_saida IS NULL OR NOW() <= CAST(vl.hora_saida AS DATETIME))
    );
    
    
CREATE OR REPLACE VIEW vw_horas_voluntario_mes AS
SELECT 
    v.idvoluntario,
    v.nome,
    DATE_FORMAT(NOW(), '%Y-%m') AS mes_referencia,
    -- Calcula a diferença em minutos e divide por 60 para ter horas decimais (ex: 1h30min = 1.5)
    ROUND(SUM(TIMESTAMPDIFF(MINUTE, p.hora_entrada, p.hora_saida)) / 60, 2) AS total_horas_mes
FROM voluntario v
INNER JOIN voluntariado vd ON v.idvoluntario = vd.voluntario_idvoluntario
INNER JOIN presenca p ON vd.idvoluntariado = p.idvoluntariado
WHERE 
    p.status_presenca = 'finalizado' -- Só contabiliza turnos finalizados com hora de saída real
    AND MONTH(p.hora_entrada) = MONTH(CURDATE())
    AND YEAR(p.hora_entrada) = YEAR(CURDATE())
GROUP BY v.idvoluntario, v.nome;


CREATE OR REPLACE VIEW vw_horas_geral_mes AS
SELECT 
    DATE_FORMAT(NOW(), '%Y-%m') AS mes_referencia,
    COUNT(p.idpresenca) AS total_turnos_finalizados,
    ROUND(SUM(TIMESTAMPDIFF(MINUTE, p.hora_entrada, p.hora_saida)) / 60, 2) AS total_horas_instituicao
FROM presenca p
WHERE 
    p.status_presenca = 'finalizado'
    AND MONTH(p.hora_entrada) = MONTH(CURDATE())
    AND YEAR(p.hora_entrada) = YEAR(CURDATE());


CREATE OR REPLACE VIEW vw_localizacao_atual AS
SELECT 
    v.idvoluntario,
    v.nome AS nome_voluntario,
    v.codigo_cracha,
    -- Tenta pegar o nome do local específico (da tab vol_local). 
    -- Se não tiver, usa o nome do hospital genérico (da tab voluntariado).
    COALESCE(l.nome, vd.hospital) AS local_atual_melhor_estimativa,
    -- Se estiver numa sala específica, mostra o código ou nome dela
    COALESCE(s.codigo_sala, s.nome_sala, '-') AS sala_especifica,
    vd.atividade AS atividade_principal,
    DATE_FORMAT(p.hora_entrada, '%H:%i') AS hora_que_chegou_hoje
FROM presenca p
INNER JOIN voluntariado vd ON p.idvoluntariado = vd.idvoluntariado
INNER JOIN voluntario v ON vd.voluntario_idvoluntario = v.idvoluntario
-- JOIN para tentar achar um local específico ATUAL na tabela vol_local
LEFT JOIN vol_local vl ON v.idvoluntario = vl.voluntario_idvoluntario
    AND NOW() >= CAST(vl.hora_entrada AS DATETIME) 
    AND (vl.hora_saida IS NULL OR NOW() <= CAST(vl.hora_saida AS DATETIME))
LEFT JOIN local l ON vl.local_idlocal = l.idlocal
LEFT JOIN sala s ON vl.sala_idsala = s.idsala
WHERE p.status_presenca = 'presente';